Fix provider crashing when some options are set in .psqlrc
In some cases, like setting `\x auto` or trying to `\echo` anything in .psqlrc will make provider crash:

    Warning: /Stage[main]/Main/Node[some-server]/Postgresql::Server::Role[backup]/Postgresql_psql[ALTER ROLE "backup" NOCREATEROLE]: Skipping because of failed dependencies
    Error: Error executing SQL; psql returned pid 16230 exit 1: 'Expanded display is used automatically.
    server: some-server.example.com
    ERROR:  role "somerole" already exists

passing option to ignore .psqlrc fixes this, and any other changes that might be set up from this file